// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "RunSteady.h"
#include "LiveWindow/LiveWindow.h"
#include "SmartDashboard/SmartDashboard.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

RunSteady::RunSteady(double setpoint): Command() {
    m_setpoint = setpoint;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pIDTestSystem.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void RunSteady::Initialize() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
    Robot::pIDTestSystem->Enable();
    Robot::pIDTestSystem->SetSetpoint(m_setpoint);
    Robot::pIDTestSystem->ReturnPIDInput();
    SmartDashboard::PutNumber("Encoder Rate", Robot::pIDTestSystem->ReturnPIDInput());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
}

// Called repeatedly when this Command is scheduled to run
void RunSteady::Execute() {
	Robot::pIDTestSystem->ReturnPIDInput();
	SmartDashboard::PutNumber("Encoder Rate", Robot::pIDTestSystem->ReturnPIDInput());

	SmartDashboard::PutNumber("Motor Speed Test", Robot::pIDTestSystem->getTheSpeed());
	SmartDashboard::PutNumber("Distance hopefully", Robot::pIDTestSystem->getTheDistance());
}

// Make this return true when this Command no longer needs to run execute()
bool RunSteady::IsFinished() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
    return Robot::pIDTestSystem->OnTarget();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
}

// Called once after isFinished returns true
void RunSteady::End() {
	Robot::pIDTestSystem->SetSetpoint(0);

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RunSteady::Interrupted() {
	Robot::pIDTestSystem->SetSetpoint(0);
}
