// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/MotorCompare.h"
#include "Commands/MoveIntake.h"
#include "Commands/RunSteady.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    otherJoy.reset(new Joystick(1));
    
    moveIntakeButton.reset(new JoystickButton(otherJoy.get(), 1));
    moveIntakeButton->WhileHeld(new MoveIntake());
    driveJoy.reset(new Joystick(0));
    
    motorCompareButton.reset(new JoystickButton(driveJoy.get(), 2));
    motorCompareButton->WhileHeld(new MotorCompare());
    runSteadyButton.reset(new JoystickButton(driveJoy.get(), 1));
    runSteadyButton->WhileHeld(new RunSteady(.5));

    // SmartDashboard Buttons
    SmartDashboard::PutData("MoveIntake", new MoveIntake());
    SmartDashboard::PutData("MotorCompare", new MotorCompare());
    SmartDashboard::PutData("RunSteady", new RunSteady(.5));
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriveJoy() {
   return driveJoy;
}

std::shared_ptr<Joystick> OI::getOtherJoy() {
   return otherJoy;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
